//! The skill-payoff duels (P1-S09, plan §7.3b): identical Cruz Missiles from the same state on the same greybox
//! segment, one driving the plain line, one the well-executed technique, botched ones, and mash scripts. The duel's
//! fixtures live in `scenarios/duels/` (generated by `make_duels.py`; `jj sim` runs them for their replay in
//! `crates/jj-tools/tests/scenarios.rs`) and its ordering sidecar in `scenarios/duels/orderings/`: the time each car takes
//! to a gate after the segment, and which car must beat which by how much (TUNE margins). A car that never reaches the
//! gate (or leaves the road by more than the gate allows) has no time and loses to any car that has one. A `gap` on a
//! beat states a known gap: that ordering must keep failing until the gap is closed and its text deleted.
//!
//! Re-tuning: `scenarios/duels/search.py` writes fixtures and orderings into `scenarios/duels/scratch/` (ignored by
//! git) with an `ACTIVE` marker, which points this test at them (and lets an ordering carry `set` tuning overrides and
//! `solo` to run each car alone), then reads the `RESULTS` lines. `scratch/BANK` (tuning lines) also runs the S03 feel
//! bank under that tuning (`the_feel_bank_under_a_tuning`): a tuning must keep every row passing.

use std::path::{Path, PathBuf};

use jj_fixture::{Fixture, Harness};
use jj_map::{Registry, load_json};
use jj_sim::observe::Metric;
use jj_sim::{Sim, TICK_HZ, VehicleProfile};
use serde::Deserialize;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Ordering {
    duel: String,
    /// Which fixture in `scenarios/duels/` holds every car (one per label, in the fixture's car order)...
    #[serde(default)]
    fixture: Option<String>,
    /// ...or one fixture per label, each with its one car alone on the segment (a duel on a racing line, where cars on
    /// one line would otherwise bump each other: the cars never meet, and every one starts from the same state).
    #[serde(default)]
    fixtures: Vec<String>,
    /// Run each car of `fixture` alone in a world of its own (the search tooling's way of getting the per-car fixtures'
    /// result from one file).
    #[serde(default)]
    solo: bool,
    gate: Gate,
    labels: Vec<String>,
    beats: Vec<Beat>,
    /// Tuning overrides (`field=value`) for the profile: only while a tuning is searched, never in the committed duels.
    #[serde(default)]
    set: Vec<String>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Gate {
    metric: Metric,
    at: f64,
    /// A car that leaves the road by more than this (m from the route's centerline; the tarmac's half width is 7) has
    /// no time: a duel is about the line, not a short cut across the grass.
    #[serde(default)]
    max_offset_m: Option<f64>,
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Beat {
    /// A label, or a label prefix ending in `*` (every `mash-*` car).
    faster: String,
    slower: String,
    /// The faster car reaches the gate at least this many seconds sooner (TUNE margins; 0 = just not slower).
    by_s: f64,
    /// A known gap (the bank states its gaps): the ordering the design asks for doesn't hold yet, and the text says why.
    /// A gap must keep failing; the day it holds, this test fails until the `gap` is deleted from the ordering.
    #[serde(default)]
    gap: Option<String>,
}

/// Where the duels live: `scenarios/duels`, or `JJ_DUEL_DIR` (a scratch directory while timings are searched).
fn duel_dir() -> PathBuf {
    let scratch = repo().join("scenarios/duels/scratch");
    if scratch.join("ACTIVE").exists() {
        scratch
    } else {
        repo().join("scenarios/duels")
    }
}

fn repo() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// The Cruz Missile, with an ordering's `set` lines (`field=value`) applied while a tuning is searched.
fn duel_profile(set: &[String]) -> VehicleProfile {
    let set: Vec<(String, String)> = set
        .iter()
        .filter_map(|l| l.split_once('='))
        .map(|(k, v)| (k.trim().to_owned(), v.trim().to_owned()))
        .collect();
    jj_fixture::profile_with(&set).expect("--set fields")
}

struct Row {
    label: String,
    gate_s: Option<f64>,
    end_speed: f64,
    wrecks: f64,
    max_offset_m: f64,
    progress_m: f64,
    legal_m: f64,
    /// Landing quality (the up axis at the first landing, 1 level) and the air time, s.
    landing_up_y: f64,
    airtime_s: f64,
}

fn run_duel(o: &Ordering, profile: &VehicleProfile, registry: &Registry) -> Vec<Row> {
    let trace = std::env::var("JJ_DUEL_TRACE").is_ok_and(|v| v == o.duel);
    match &o.fixture {
        Some(file) if o.solo => {
            let text = std::fs::read_to_string(duel_dir().join(file)).expect("fixture");
            let whole: serde_json::Value = serde_json::from_str(&text).expect("json");
            let rows: Vec<Vec<Row>> = std::thread::scope(|scope| {
                let handles: Vec<_> = o
                    .labels
                    .iter()
                    .enumerate()
                    .map(|(i, label)| {
                        let whole = &whole;
                        scope.spawn(move || {
                            let mut one = whole.clone();
                            one["cars"] = serde_json::json!([whole["cars"][i].clone()]);
                            let keep = |v: &serde_json::Value| v["car"].as_u64() == Some(i as u64);
                            let remap = |v: &serde_json::Value| {
                                let mut v = v.clone();
                                v["car"] = serde_json::json!(0);
                                v
                            };
                            for key in ["inputs", "autopilot"] {
                                if let Some(list) = whole[key].as_array() {
                                    one[key] = serde_json::Value::Array(
                                        list.iter().filter(|v| keep(v)).map(remap).collect(),
                                    );
                                }
                            }
                            if let Some(list) = whole["debris"].as_array() {
                                one["debris"] = serde_json::Value::Array(
                                    list.iter().filter(|v| keep(v)).map(remap).collect(),
                                );
                            }
                            let fx: Fixture = serde_json::from_value(one).expect("solo fixture");
                            run_loaded(
                                o,
                                fx,
                                0,
                                std::slice::from_ref(label),
                                profile,
                                registry,
                                false,
                            )
                        })
                    })
                    .collect();
                handles
                    .into_iter()
                    .map(|h| h.join().expect("solo car"))
                    .collect()
            });
            rows.into_iter().flatten().collect()
        }
        Some(file) => run_fixture(o, file, 0, &o.labels, profile, registry, trace),
        None => o
            .fixtures
            .iter()
            .zip(&o.labels)
            .flat_map(|(file, label)| {
                run_fixture(
                    o,
                    file,
                    0,
                    std::slice::from_ref(label),
                    profile,
                    registry,
                    trace,
                )
            })
            .collect(),
    }
}

/// Runs one fixture; its cars, from `first`, take `labels` in order.
fn run_fixture(
    o: &Ordering,
    file: &str,
    first: u32,
    labels: &[String],
    profile: &VehicleProfile,
    registry: &Registry,
    trace: bool,
) -> Vec<Row> {
    let fx: Fixture =
        serde_json::from_slice(&std::fs::read(duel_dir().join(file)).expect("fixture"))
            .expect("parse");
    run_loaded(o, fx, first, labels, profile, registry, trace)
}

fn run_loaded(
    o: &Ordering,
    fx: Fixture,
    first: u32,
    labels: &[String],
    profile: &VehicleProfile,
    registry: &Registry,
    trace: bool,
) -> Vec<Row> {
    let map = load_json(&std::fs::read(repo().join(&fx.map)).expect("map"), registry)
        .expect("map validates");
    let ticks = fx.ticks;
    let mut sim = Sim::new(&map, registry, fx.seed, profile.clone());
    let mut h = Harness::new(fx, &map, &mut sim, false).expect("harness");
    let n = labels.len() as u32;
    let mut gate: Vec<Option<u64>> = vec![None; n as usize];
    h.record(&sim, false);
    while sim.tick() < ticks {
        h.before_step(&mut sim);
        sim.step();
        h.after_step(&sim, sim.tick() == ticks);
        if trace && sim.tick().is_multiple_of(60) {
            let row: Vec<String> = (0..n)
                .map(|c| {
                    let g = |m| h.metric(first + c, m).unwrap_or(f64::NAN);
                    format!(
                        "{:5.1}m {:4.1}ms o{:4.1} s{:3.0} u{:.2}",
                        g(Metric::ProgressM),
                        g(Metric::Speed),
                        g(Metric::RouteOffsetM),
                        g(Metric::SlipDeg),
                        g(Metric::UpY)
                    )
                })
                .collect();
            println!("t{:4} {}", sim.tick(), row.join(" | "));
        }
        for car in 0..n {
            if gate[car as usize].is_none()
                && h.metric(first + car, o.gate.metric)
                    .is_some_and(|v| v >= o.gate.at)
            {
                gate[car as usize] = Some(sim.tick());
            }
        }
    }
    (0..n)
        .map(|k| {
            let car = first + k;
            Row {
                label: labels[k as usize].clone(),
                gate_s: gate[k as usize]
                    .filter(|_| {
                        o.gate.max_offset_m.is_none_or(|m| {
                            h.metric(car, Metric::MaxRouteOffsetM)
                                .is_none_or(|v| v <= m)
                        })
                    })
                    .map(|t| t as f64 / f64::from(TICK_HZ)),
                end_speed: h.metric(car, Metric::Speed).unwrap_or(0.0),
                wrecks: h.metric(car, Metric::Wrecks).unwrap_or(0.0),
                max_offset_m: h.metric(car, Metric::MaxRouteOffsetM).unwrap_or(0.0),
                progress_m: h.metric(car, Metric::ProgressM).unwrap_or(0.0),
                legal_m: h.metric(car, Metric::LegalProgressM).unwrap_or(0.0),
                landing_up_y: h.metric(car, Metric::LandingUpY).unwrap_or(f64::NAN),
                airtime_s: h.metric(car, Metric::AirtimeS).unwrap_or(0.0),
            }
        })
        .collect()
}

fn matching<'a>(rows: &'a [Row], pat: &str) -> Vec<&'a Row> {
    match pat.strip_suffix('*') {
        Some(prefix) => rows
            .iter()
            .filter(|r| r.label.starts_with(prefix))
            .collect(),
        None => rows.iter().filter(|r| r.label == pat).collect(),
    }
}

#[test]
fn every_duel_holds_its_ordering() {
    let registry = Registry::generic();
    let mut files: Vec<PathBuf> = std::fs::read_dir(duel_dir().join("orderings"))
        .expect("orderings")
        .map(|e| e.expect("entry").path())
        .filter(|p| p.extension().is_some_and(|x| x == "json"))
        .collect();
    files.sort();
    let scratch = duel_dir().ends_with("scratch");
    assert!(
        scratch || files.len() >= 7,
        "every S09 duel has an ordering: {files:?}"
    );
    // Each duel is its own world: they run side by side.
    let runs: Vec<(Ordering, Vec<Row>)> = std::thread::scope(|scope| {
        let handles: Vec<_> = files
            .iter()
            .map(|file| {
                let registry = &registry;
                scope.spawn(move || {
                    let o: Ordering =
                        serde_json::from_slice(&std::fs::read(file).expect("read")).expect("parse");
                    let rows = run_duel(&o, &duel_profile(&o.set), registry);
                    (o, rows)
                })
            })
            .collect();
        handles
            .into_iter()
            .map(|h| h.join().expect("duel"))
            .collect()
    });
    let mut failures = Vec::new();
    let mut table = String::from(
        "| duel | car | time to gate (s) | speed at end (m/s) | wrecks |\n|---|---|---|---|---|\n",
    );
    for (o, rows) in &runs {
        for r in rows {
            table += &format!(
                "| {} | {} | {} | {:.1} | {} |\n",
                o.duel,
                r.label,
                r.gate_s.map_or("DNF".to_owned(), |s| format!("{s:.2}")),
                r.end_speed,
                r.wrecks
            );
        }
        if scratch {
            let all: Vec<String> = rows
                .iter()
                .map(|r| {
                    format!(
                        "{}|{:?}|{:.2}|{}|{:.1}|{:.1}|{:.1}|{:.3}|{:.2}",
                        r.label,
                        r.gate_s,
                        r.end_speed,
                        r.wrecks,
                        r.max_offset_m,
                        r.progress_m,
                        r.legal_m,
                        r.landing_up_y,
                        r.airtime_s
                    )
                })
                .collect();
            println!("RESULTS {} {}", o.duel, all.join(";"));
        }
        for b in &o.beats {
            let (fast, slow) = (matching(rows, &b.faster), matching(rows, &b.slower));
            assert!(
                !fast.is_empty() && !slow.is_empty(),
                "{}: {b:?} matches no car",
                o.duel
            );
            for f in &fast {
                for s in &slow {
                    let ok = match (f.gate_s, s.gate_s) {
                        (Some(f), Some(s)) => s - f >= b.by_s,
                        (Some(_), None) => true,
                        _ => false,
                    };
                    match (&b.gap, ok) {
                        (None, false) => failures.push(format!(
                            "{}: {} ({:?} s) must beat {} ({:?} s) by {} s",
                            o.duel, f.label, f.gate_s, s.label, s.gate_s, b.by_s
                        )),
                        (Some(_), true) => failures.push(format!(
                            "{}: the gap closed ({} {:?} s beats {} {:?} s by {} s): delete its `gap`",
                            o.duel, f.label, f.gate_s, s.label, s.gate_s, b.by_s
                        )),
                        _ => {}
                    }
                }
            }
        }
    }
    if let Ok(path) = std::env::var("JJ_DUEL_TABLE") {
        std::fs::write(path, &table).expect("write the duel table");
    }
    println!("{table}");
    assert!(failures.is_empty(), "duels:\n  {}", failures.join("\n  "));
}

/// While a tuning is searched (`scratch/BANK` holds its `field=value` lines): the S03 feel bank and affordance rows run
/// under it, and each result prints as a `BANK` line (the tuning must keep every one passing, S09's third criterion).
#[test]
fn the_feel_bank_under_a_tuning() {
    let Ok(text) = std::fs::read_to_string(repo().join("scenarios/duels/scratch/BANK")) else {
        return;
    };
    let set: Vec<String> = text
        .lines()
        .filter(|l| l.contains('='))
        .map(str::to_owned)
        .collect();
    let profile = duel_profile(&set);
    let registry = Registry::generic();
    let mut files: Vec<PathBuf> = ["scenarios/feel", "scenarios/affordances"]
        .iter()
        .flat_map(|d| std::fs::read_dir(repo().join(d)).expect("dir"))
        .map(|e| e.expect("entry").path())
        .filter(|p| p.extension().is_some_and(|x| x == "json"))
        .collect();
    files.sort();
    for file in files {
        let fx: Fixture =
            serde_json::from_slice(&std::fs::read(&file).expect("read")).expect("parse");
        let map = load_json(
            &std::fs::read(repo().join(&fx.map)).expect("map"),
            &registry,
        )
        .expect("map");
        let out = jj_fixture::run(&fx, &map, &registry, &profile, false).expect("runs");
        let bad: Vec<String> = out
            .recorded
            .checks
            .iter()
            .filter(|c| !c.ok)
            .map(|c| {
                format!(
                    "car {} {:?}={:?} not in [{},{}]",
                    c.car, c.metric, c.actual, c.min, c.max
                )
            })
            .chain(
                out.baselines
                    .iter()
                    .filter(|b| !b.ok)
                    .map(|b| format!("{:?} baseline same", b.kind)),
            )
            .collect();
        println!(
            "BANK {} {}",
            fx.scenario,
            if bad.is_empty() {
                "ok".to_owned()
            } else {
                bad.join("; ")
            }
        );
    }
}
