#!/usr/bin/env node
// Generates the third-party licence list for the credits page from the lockfiles (P1-C09): every crate in the shipped
// bundles' dependency closure (cargo metadata, offline and locked) and every non-dev package of the web lockfile.
//   node tools/licences/generate.mjs          writes web/landing/credits/licences.json
//   node tools/licences/generate.mjs --stdout prints it
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { cargoLockPackages, npmAllPackages, npmShippedPackages } from './lib.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '../..');
const policy = JSON.parse(readFileSync(resolve(here, 'policy.json'), 'utf8'));

const r = spawnSync('cargo', ['metadata', '--format-version', '1', '--locked', '--offline'], { cwd: repo, encoding: 'utf8', maxBuffer: 1 << 28 });
if (r.status !== 0) {
  console.error(`cargo metadata failed:\n${r.stderr}`);
  process.exit(1);
}
const meta = JSON.parse(r.stdout);
const byId = new Map(meta.packages.map((p) => [p.id, p]));
const nodes = new Map(meta.resolve.nodes.map((n) => [n.id, n]));
const roots = meta.packages.filter((p) => policy.rustRoots.includes(p.name)).map((p) => p.id);
if (roots.length !== policy.rustRoots.length) {
  console.error(`rustRoots not all found: ${policy.rustRoots}`);
  process.exit(1);
}
// The shipped closure: normal and build dependencies (not dev) of the crates that make the shipped binary and wasm.
const seen = new Set(roots);
const queue = [...roots];
while (queue.length) {
  const n = nodes.get(queue.pop());
  for (const d of n?.deps ?? []) {
    if (!d.dep_kinds.some((k) => k.kind === null || k.kind === 'build')) continue;
    if (!seen.has(d.pkg)) {
      seen.add(d.pkg);
      queue.push(d.pkg);
    }
  }
}
const lockedCargo = cargoLockPackages(readFileSync(resolve(repo, 'Cargo.lock'), 'utf8'));
const rust = [];
for (const id of seen) {
  const p = byId.get(id);
  if (!p.source) continue; // our own crates
  rust.push({ name: p.name, version: p.version, licence: p.license ?? (p.license_file ? `see ${p.license_file}` : null) });
}
rust.sort((a, b) => (a.name + a.version).localeCompare(b.name + b.version));
const shippedRust = new Set(rust.map((e) => `${e.name}@${e.version}`));
const rustNotShipped = lockedCargo.filter((id) => !shippedRust.has(id));

const npmLock = JSON.parse(readFileSync(resolve(repo, 'web/package-lock.json'), 'utf8'));
const shippedWeb = new Set(npmShippedPackages(npmLock));
const web = [];
for (const [path, p] of Object.entries(npmLock.packages)) {
  if (!path.includes('node_modules/') || p.link || !p.version || p.dev) continue;
  const name = path.slice(path.lastIndexOf('node_modules/') + 'node_modules/'.length);
  web.push({ name, version: p.version, licence: p.license ?? null });
}
web.sort((a, b) => a.name.localeCompare(b.name));
const webNotShipped = npmAllPackages(npmLock).filter((id) => !shippedWeb.has(id));

const list = {
  what: 'Generated by tools/licences/generate.mjs from Cargo.lock (cargo metadata) and web/package-lock.json. Do not edit by hand; the CI check (tools/licences/check.mjs) fails when it drifts from the lockfiles.',
  rust,
  web,
  rustNotShipped,
  webNotShipped,
};
const text = `${JSON.stringify(list, null, 1)}\n`;
if (process.argv.includes('--stdout')) process.stdout.write(text);
else {
  writeFileSync(resolve(repo, 'web/landing/credits/licences.json'), text);
  console.log(`licences: ${rust.length} crates and ${web.length} web packages ship; ${rustNotShipped.length + webNotShipped.length} lockfile entries are tooling only`);
}
