#!/usr/bin/env node
// P1-C01 token build step: the UI token file -> web/shared/ui/tokens.generated.css (CSS variables per profile and the
// @font-face rules). Deterministic: the same tokens always give the same bytes, so the file is committed and
// `--check` (run by the landing tests) fails when it is stale. `npm --prefix web run build` regenerates it first.
//
// Tokens come from the owner's accepted set (G-DESIGN, 2026-10-07). The fonts are the copies in web/shared/ui/fonts (the
// same files as art/ui/fonts; nothing at run time reaches into art/), so the font URLs are written relative to this folder.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const TOKENS = '../../../art/ui/accepted/2026-10-07/tokens.json';

const here = dirname(fileURLToPath(import.meta.url));
const tokensFile = join(here, TOKENS);
const outFile = join(here, 'tokens.generated.css');
const outTs = join(here, 'tokens.generated.ts');
const tokens = JSON.parse(readFileSync(tokensFile, 'utf8'));

const num = (n) => String(+n.toFixed(3));
const px = (n) => `${num(n)}px`;
const fontStack = (family) => `"${family}",${tokens.fonts.fallback.map((f) => (f.includes(' ') ? `"${f}"` : f)).join(',')}`;
// The token file names its fonts as fonts/<file>; they live in ./fonts here, so Vite bundles them from the package.
const fontUrl = (file) => `./${file}`;
const rgb = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16)).join(' ');

const css = [`/* GENERATED by web/shared/ui/build-tokens.mjs from ${relative(join(here, '..', '..', '..'), tokensFile).split(sep).join('/')} (${tokens.status}, v${tokens.version}). Do not edit. */`];
for (const face of [tokens.fonts.display, tokens.fonts.body]) {
  for (const f of face.files) {
    css.push(`@font-face{font-family:"${face.family}";src:url("${fontUrl(f.file)}") format("woff2");font-weight:${f.weight};font-style:${f.style};font-display:swap}`);
  }
}

// Shared by every profile: colours, identity colours, fonts, motion, touch size.
const shared = [];
for (const [name, c] of Object.entries(tokens.palette)) shared.push(`--c-${name}:${c.hex}`);
tokens.identity.colors.forEach((c, i) => shared.push(`--id-${i}:${c.hex}`, `--id-${i}-on:${tokens.palette[c.on].hex}`));
shared.push(`--font-display:${fontStack(tokens.fonts.display.family)}`, `--font-body:${fontStack(tokens.fonts.body.family)}`);
shared.push(`--lh-display:${tokens.type.lineHeight.display}`, `--lh-body:${tokens.type.lineHeight.body}`, `--ls-display:${tokens.type.letterSpacing.display}`);
const L = tokens.language;
shared.push(`--slant-heading:${L.slant.headingRotateDeg}deg`, `--skew-tag:${L.slant.tagSkewDeg}deg`, `--rot-tag:${L.slant.tagRotateDeg}deg`, `--skew-strip:${L.slant.stripSkewDeg}deg`);
const sh = tokens.ink.stickerShadow, shInk = tokens.ink.stickerShadowOnInk;
shared.push(`--shadow-c:rgb(${rgb(tokens.palette[sh.color].hex)} / ${sh.opacity})`);
shared.push(`--shadow-c-on-ink:rgb(${rgb(tokens.palette[shInk.color].hex)} / ${shInk.opacity})`);
for (const [k, v] of Object.entries(tokens.motion.durationsMs)) shared.push(`--dur-${k}:${v}ms`);
for (const [k, v] of Object.entries(tokens.motion.easing)) shared.push(`--ease-${k}:${v}`);

// Per profile. TV values are written on a 1080p reference and scaled by --ui-scale (output height / 1080, set by
// applyProfile), so a 4K or a 720p output keeps the same proportions (tokens.type.profiles.tv.viewing).
const profileVars = (profile) => {
  const k = profile === 'tv' ? (v) => `calc(${px(v)} * var(--ui-scale,1))` : px;
  const v = [];
  for (const [name, size] of Object.entries(tokens.type.profiles[profile].scale)) v.push(`--fs-${name}:${k(size)}`);
  tokens.space.steps.forEach((s, i) => v.push(`--sp-${i}:${k(s * tokens.space.profileMultiplier[profile])}`));
  // Touch targets scale with the profile's space multiplier (96 px at 1080p on a TV: pointer or gamepad from the couch).
  const m = tokens.space.profileMultiplier[profile];
  v.push(`--touch:${k(tokens.layout.minTouchTargetPx * m)}`, `--touch-gap:${k(tokens.layout.minTouchGapPx * m)}`);
  const outline = tokens.ink.outlinePx[profile];
  v.push(`--outline:${k(outline)}`, `--radius:${k(L.corners.buttonPx[profile])}`);
  v.push(`--r-panel:${k(L.corners.panelPx[profile])}`, `--r-banner:${k(L.corners.bannerPx[profile])}`, `--r-badge:${k(L.corners.badgePx[profile])}`);
  v.push(`--torn-amp:${L.banner.heading.tornAmplitudePx[profile]}`, `--capt-size:${k(L.banner.caption.sizePx[profile])}`);
  // The sticker shadow's y offset scales with the outline, from 5 px at the desk profile's 3 px outline.
  v.push(`--sh-y:${k((sh.y * outline) / tokens.ink.outlinePx.desk)}`, `--lift-y:${k(-2)}`);
  const kb = tokens.focus.keyboard, gp = tokens.focus.gamepad;
  v.push(`--focus-kb-w:${k(kb.widthPx[profile])}`, `--focus-kb-off:${k(kb.offsetPx[profile])}`);
  v.push(`--focus-gp-w:${k(gp.widthPx[profile])}`, `--focus-gp-off:${k(gp.offsetPx[profile])}`);
  return v;
};
// Handheld is the default (phones are the join path); a page opts into the others with data-profile.
css.push(`:root{${[...shared, ...profileVars('handheld')].join(';')}}`);
for (const profile of ['desk', 'tv']) css.push(`:root[data-profile="${profile}"]{${profileVars(profile).join(';')}}`);

const out = `${css.join('\n')}\n`;

// The numbers the DOM code needs (seat colours, named motion with its Reduced variant, the caption, tilt limits) as typed data.
const data = {
  seatColors: tokens.identity.colors.map((c) => ({ name: c.name, hex: c.hex, on: tokens.palette[c.on].hex })),
  motion: tokens.motion.named,
  caption: tokens.language.banner.caption,
  panelTiltMaxDeg: tokens.language.slant.panelTiltMaxDeg,
  headingJitterDeg: tokens.language.slant.headingJitterDeg,
  qr: tokens.qr,
  palette: { ink: tokens.palette.ink.hex, paper: tokens.palette.paper.hex },
};
const outT = `// GENERATED by web/shared/ui/build-tokens.mjs from ${relative(join(here, '..', '..', '..'), tokensFile).split(sep).join('/')}. Do not edit.
export const tokenData = ${JSON.stringify(data, null, 2)} as const;
`;

const files = [[outFile, out], [outTs, outT]];
if (process.argv.includes('--check')) {
  for (const [file, text] of files) {
    let current = '';
    try {
      current = readFileSync(file, 'utf8');
    } catch {}
    if (current !== text) {
      console.error(`${relative(process.cwd(), file)} is stale: run \`npm --prefix web run tokens\``);
      process.exit(1);
    }
  }
  console.log('tokens.generated.css and tokens.generated.ts are up to date');
} else {
  for (const [file, text] of files) writeFileSync(file, text);
  console.log(`wrote ${relative(process.cwd(), outFile)} and ${relative(process.cwd(), outTs)} from ${relative(process.cwd(), tokensFile)}`);
}
