// GENERATED by web/shared/ui/build-tokens.mjs from art/ui/accepted/2026-10-07/tokens.json. Do not edit.
export const tokenData = {
  "seatColors": [
    {
      "name": "red",
      "hex": "#E5322D",
      "on": "#FFF4DE"
    },
    {
      "name": "blue",
      "hex": "#2563EB",
      "on": "#FFF4DE"
    },
    {
      "name": "orange",
      "hex": "#FF7A1A",
      "on": "#15203A"
    },
    {
      "name": "teal",
      "hex": "#00B5B8",
      "on": "#15203A"
    },
    {
      "name": "yellow",
      "hex": "#FFD23F",
      "on": "#15203A"
    },
    {
      "name": "pink",
      "hex": "#FF4FA3",
      "on": "#15203A"
    },
    {
      "name": "charcoal",
      "hex": "#2A2D34",
      "on": "#FFF4DE"
    },
    {
      "name": "green",
      "hex": "#22A447",
      "on": "#15203A"
    },
    {
      "name": "white",
      "hex": "#F4F1EA",
      "on": "#15203A"
    },
    {
      "name": "purple",
      "hex": "#8B3FD9",
      "on": "#FFF4DE"
    },
    {
      "name": "maroon",
      "hex": "#8E1B3F",
      "on": "#FFF4DE"
    },
    {
      "name": "sky",
      "hex": "#5EC8FF",
      "on": "#15203A"
    }
  ],
  "motion": {
    "sticker-in": {
      "durationMs": 320,
      "easing": "sticker",
      "does": "Scale 0.6 to 1 with a slight overshoot and a 4 degree settle",
      "reduced": {
        "durationMs": 120,
        "does": "Fade in, no scale or rotation"
      }
    },
    "identify-pulse": {
      "durationMs": 500,
      "repeat": 3,
      "does": "About 1.5 s (master §5.2, R99): 'Cooee #7' over a transparent, high-exposure flash in the seat colour, tweened (fast attack, long decay); the seat's tile border and number badge pulse, a bright outline on the car in other tiles; the controller plays the same flash in the player's colour",
      "reduced": {
        "durationMs": 500,
        "repeat": 3,
        "does": "No flash at all (POC2-15): the label shows for the same time without scale, the border holds thick, the outline shows"
      }
    },
    "countdown-beat": {
      "durationMs": 1000,
      "does": "Each number punches in (scale 1.4 to 1) and fades on the beat",
      "reduced": {
        "durationMs": 1000,
        "does": "Numbers swap on the beat, no scale"
      }
    },
    "reflow": {
      "durationMs": 320,
      "easing": "standard",
      "does": "Tiles slide to their new cells when players join or leave",
      "reduced": {
        "durationMs": 0,
        "does": "Tiles cut to their new cells"
      }
    },
    "results-reveal": {
      "durationMs": 1200,
      "easing": "sticker",
      "does": "Podium cards drop in from the top, staggered by 150 ms",
      "reduced": {
        "durationMs": 200,
        "does": "Cards fade in together"
      }
    },
    "toast": {
      "durationMs": 200,
      "easing": "enter",
      "does": "Slides in 16 px and fades; stays 4 s",
      "reduced": {
        "durationMs": 120,
        "does": "Fades only"
      }
    },
    "wreck-shake": {
      "durationMs": 300,
      "does": "A small screen shake on the wrecked player's tile only",
      "reduced": {
        "durationMs": 0,
        "does": "No shake; the comic impact word still shows"
      }
    }
  },
  "caption": {
    "fills": [
      "saffron",
      "ink",
      "teal"
    ],
    "textOn": {
      "saffron": "ink",
      "ink": "paper",
      "teal": "ink"
    },
    "edge": "brush",
    "tiltMaxDeg": 3,
    "sizePx": {
      "tv": 30,
      "desk": 20,
      "handheld": 18
    },
    "maxLines": 2,
    "placements": [
      "in-video: bottom-left over a replay or highlight",
      "cell: centred in a spare grid cell",
      "footer: the middle of the host footer band"
    ],
    "note": "The intermission subtitle (owner round 3: 'far better') as the one caption (br-dim.8): display italic caps on a brush strip, skewed like a tag, a seeded tilt of up to 3 degrees (0 in the footer), saffron by default, ink for a quiet line, teal for a positive callout. Never on one player's tile; wraps to two lines at most, then is cut with an ellipsis, so caption copy stays short"
  },
  "panelTiltMaxDeg": 1.5,
  "headingJitterDeg": 1,
  "qr": {
    "rule": "Plain black-on-white code with a quiet zone of at least 4 modules on every side and nothing in the middle; error correction M; the room code sits beside it, never inside, in the display face",
    "quietZoneModules": 4,
    "errorCorrection": "M",
    "minModulePx": {
      "tv": 8,
      "desk": 4,
      "handheld": 4
    },
    "colors": {
      "modules": "black",
      "background": "white"
    }
  },
  "palette": {
    "ink": "#15203A",
    "paper": "#FFF4DE"
  }
} as const;
