#!/usr/bin/env bash
# P1-U01 style frames through the art pipeline: MASTER + UI block + H4 direction + subject + GUARDS
# (prompts/<name>.txt), generated by `codex exec` with its image tool. Usage: generate.sh <name> [suffix]
# References: H4 (the most authoritative style ref), Spike J's Cruz Missile render, and M2's controls
# for the phone frame. Output: <name><suffix>.png beside this script, plus a .log.
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
repo=$(cd "$here/../../.." && pwd)
name=$1 suffix=${2:-}
h4=$repo/docs/plans/ux-study-2026-09-29/images/H4-host-round-results-v2.png
car=$repo/spikes/art-pipeline/J-cruze-lowpoly/out/evidence/ladder_L0_hero.png
m2=$repo/docs/plans/ux-study-2026-09-29/images/M2-mobile-control-settings-v2.png
case $name in
    phone-controller) refs=(-i "$h4" -i "$m2"); size="1024x1536 portrait"
        what="the first is the H4 house UI style reference; the second shows the controller layout the owner likes (its two sticks)" ;;
    *) refs=(-i "$h4" -i "$car"); size="the widest 16:9-like landscape size the tool supports (1536x1024 if nothing wider)"
        what="the first is the H4 house UI style reference; the second is the real in-game car (a faceted low-poly hatchback) that every car in the frame must look like" ;;
esac
# The configured default model may not be available on the ChatGPT account (2026-10-03: gpt-6.1-sol and
# gpt-6-astra are refused, gpt-6-luna has no image tool; ~/.codex/*model* lists what is). Override with CODEX_MODEL.
codex exec -m "${CODEX_MODEL:-gpt-5.6-terra}" --skip-git-repo-check -C "$here" -s workspace-write "${refs[@]}" -- \
    "Use your image generation tool to create ONE image from the prompt in ./prompts/$name.txt (read it and use it verbatim as the image prompt). Attached images: $what. Pass the attached images to the image generator as references. Size: $size. Save it as PNG at ./$name$suffix.png and print the path." \
    </dev/null >"$here/$name$suffix.log" 2>&1
ls -la "$here/$name$suffix.png"
