#!/usr/bin/env node
// Build the gallery's copy of the engine synth (P1-A04): bundle web/shared/audio/engine-synth/ into one
// ES module next to the page (engine-synth.js, committed so the page works from any static server with no
// build step) and write the profile JSON Schema from the validator's rule table, so the two cannot drift.
// Uses the web workspace's own Vite, so it is the same transform pipeline the game build uses.
// Usage: node art/ui/poc/audio/engine/build.mjs [--check]   (--check fails if the committed files are stale)
import { readFileSync, writeFileSync, mkdtempSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..', '..', '..', '..', '..');
const moduleDir = join(repo, 'web', 'shared', 'audio', 'engine-synth');
const checkOnly = process.argv.includes('--check');

const { build } = await import(pathToFileURL(join(repo, 'web', 'node_modules', 'vite', 'dist', 'node', 'index.js')).href);

const outDir = checkOnly ? mkdtempSync(join(tmpdir(), 'engine-synth-')) : here;
await build({
  configFile: false,
  root: moduleDir,
  logLevel: 'warn',
  build: {
    lib: { entry: join(moduleDir, 'index.ts'), formats: ['es'], fileName: () => 'engine-synth.js' },
    outDir,
    emptyOutDir: false,
    minify: false,
    sourcemap: false,
    target: 'es2023',
  },
});

// JSON Schema (2020-12) from the validator's rule table.
const bundle = await import(pathToFileURL(join(outDir, 'engine-synth.js')).href);
const toSchema = (rule) => {
  const meta = rule.doc || rule.unit ? { ...(rule.doc ? { description: rule.doc } : {}), ...(rule.unit ? { 'x-unit': rule.unit } : {}) } : {};
  switch (rule.k) {
    case 'num':
      return { type: rule.int ? 'integer' : 'number', minimum: rule.min, maximum: rule.max, ...meta };
    case 'str':
      return { type: 'string', minLength: 1, ...meta };
    case 'lit':
      return { const: rule.v, ...meta };
    case 'enum':
      return { enum: [...rule.v], ...meta };
    case 'arr':
      return { type: 'array', minItems: rule.min, items: toSchema(rule.of), ...meta };
    case 'obj': {
      const required = Object.keys(rule.props).filter((k) => !rule.optional?.includes(k));
      return {
        type: 'object',
        properties: Object.fromEntries(Object.entries(rule.props).map(([k, v]) => [k, toSchema(v)])),
        required,
        additionalProperties: false,
        ...meta,
      };
    }
    default:
      throw new Error(`unknown rule ${rule.k}`);
  }
};
const schema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://jj.invalid/schemas/engine-profile.v1.json',
  title: 'Joystick Jammers engine profile (v1)',
  description:
    'Generated by art/ui/poc/audio/engine/build.mjs from PROFILE_RULE in profile.ts. Cross-field rules (idle < redline <= limiter, falling gear ratios, ordered min/max pairs) are checked by validateProfile() only; JSON Schema cannot express them.',
  ...toSchema(bundle.PROFILE_RULE),
};
const schemaText = `${JSON.stringify(schema, null, 2)}\n`;
const schemaPath = join(moduleDir, 'profile.schema.json');
// The gallery publishes art/ui/ on its own, so the page reads copies kept next to it: the schema and
// every profile named in the vehicle-sound manifest (P1-A04b; a new vehicle is a new file in
// assets/audio/engine/ plus one line in manifest.json, and this build publishes it).
const manifestSrc = join(repo, 'assets', 'audio', 'engine', 'manifest.json');
const manifest = JSON.parse(readFileSync(manifestSrc, 'utf8'));
if (!Array.isArray(manifest.files) || manifest.files.length === 0) throw new Error('assets/audio/engine/manifest.json: expected { "files": [ ... ] }');
const published = [];
for (const file of manifest.files) {
  if (typeof file !== 'string' || !/^[a-z0-9-]+\.json$/.test(file)) throw new Error(`manifest: bad file name ${JSON.stringify(file)}`);
  published.push([join(repo, 'assets', 'audio', 'engine', file), join(here, file)]);
}

if (checkOnly) {
  const stale = [];
  const fresh = readFileSync(join(outDir, 'engine-synth.js'), 'utf8');
  const committed = existsSync(join(here, 'engine-synth.js')) ? readFileSync(join(here, 'engine-synth.js'), 'utf8') : '';
  if (fresh !== committed) stale.push('art/ui/poc/audio/engine/engine-synth.js');
  const committedSchema = existsSync(schemaPath) ? readFileSync(schemaPath, 'utf8') : '';
  if (schemaText !== committedSchema) stale.push('web/shared/audio/engine-synth/profile.schema.json');
  const committedSchemaCopy = existsSync(join(here, 'profile.schema.json')) ? readFileSync(join(here, 'profile.schema.json'), 'utf8') : '';
  if (schemaText !== committedSchemaCopy) stale.push('art/ui/poc/audio/engine/profile.schema.json');
  const committedManifest = existsSync(join(here, 'manifest.json')) ? readFileSync(join(here, 'manifest.json'), 'utf8') : '';
  const manifestText = `${JSON.stringify(manifest, null, 2)}\n`;
  if (committedManifest !== manifestText) stale.push('art/ui/poc/audio/engine/manifest.json');
  for (const [src, copy] of published) {
    const text = readFileSync(src, 'utf8');
    if (!existsSync(copy) || readFileSync(copy, 'utf8') !== text) stale.push(`art/ui/poc/audio/engine/${basename(copy)}`);
  }
  rmSync(outDir, { recursive: true, force: true });
  if (stale.length) {
    console.error(`stale: ${stale.join(', ')} (run node art/ui/poc/audio/engine/build.mjs)`);
    process.exit(1);
  }
  console.log('engine-synth.js, profile.schema.json, manifest and profiles are up to date');
} else {
  writeFileSync(schemaPath, schemaText);
  writeFileSync(join(here, 'profile.schema.json'), schemaText);
  writeFileSync(join(here, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  for (const [src, copy] of published) writeFileSync(copy, readFileSync(src, 'utf8'));
  console.log(`built engine-synth.js, profile.schema.json and ${published.length} profile(s) from the manifest`);
}
